# <div class="alert alert-block alert-success" dir="rtl" style="text-align: center;"><strong><span style="font-size: 20pt">Data PreProcessing <br /></span></strong></div>

In [2]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

# <font color='cadetblue'>1- Import the dataset</font>



In [3]:
dataset = pd.read_csv(r"data_.csv")

In [6]:
df = pd.DataFrame(dataset)

In [7]:
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [8]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [9]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [10]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


# <font color='dodgerblue'>2- Identifying and handling the missing values</font>


In [11]:
df.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

# <font color='lime'>Dropna</font>

In [12]:
df1 = df.copy()

In [13]:
# summarize the shape of the raw data
print("Before:",df1.shape)

# drop rows with missing values
df1.dropna(inplace=True)

# summarize the shape of the data with missing rows removed
print("After:",df1.shape)

Before: (10, 4)
After: (8, 4)


# <font color='chartreuse'>Fillna</font>

In [14]:
df2 = df.copy()

In [15]:
import warnings
warnings.filterwarnings('ignore')

In [16]:
# fill missing values with mean column values
df2.fillna(df2.mean(), inplace=True)
# count the number of NaN values in each column
print(df2.isnull().sum())

df2

Country      0
Age          0
Salary       0
Purchased    0
dtype: int64


Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

# <font color='darkgreen'>Scikit-Learn</font>



In [17]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [18]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [19]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


# <font color='royalblue'>3- Encoding the categorical data</font>


# <font color='darkorchid'>ColumnTransformer</font>

In [20]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [23]:
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [24]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


# <font color='deeppink'>Pd.get_dummies()</font>

In [25]:
df2

Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

In [26]:
pd.get_dummies(df2)

Age        Salary  Country_France  Country_Germany  Country_Spain  \
0  44.000000  72000.000000               1                0              0   
1  27.000000  48000.000000               0                0              1   
2  30.000000  54000.000000               0                1              0   
3  38.000000  61000.000000               0                0              1   
4  40.000000  63777.777778               0                1              0   
5  35.000000  58000.000000               1                0              0   
6  38.777778  52000.000000               0                0              1   
7  48.000000  79000.000000               1                0              0   
8  50.000000  83000.000000               0                1              0   
9  37.000000  67000.000000               1                0              0   

   Purchased_No  Purchased_Yes  
0             1              0  
1             0              1  
2             1              0  
3             1              0  
4             0              1  
5             0              1  
6             1              0  
7             0              1  
8             1              0  
9             0              1

# <font color='magenta'>LabelEncoder</font>

In [27]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [28]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


# <font color='aqua'>4- Splitting the dataset</font>


In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [30]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [ ]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [ ]:
print(y_test)

[0 1]


# <font color='lightskyblue'>4- Feature scaling</font>


In [ ]:
from sklearn.preprocessing import MinMaxScaler
mm = MinMaxScaler()
X_train[:, 3:] = mm.fit_transform(X_train[:, 3:])
X_test[:, 3:] = mm.transform(X_test[:, 3:])

In [31]:
print(X_train[:, 3:])

[[38.77777777777778 52000.0]
 [40.0 63777.77777777778]
 [44.0 72000.0]
 [38.0 61000.0]
 [27.0 48000.0]
 [48.0 79000.0]
 [50.0 83000.0]
 [35.0 58000.0]]


In [ ]:
print(X_test[:, 3:])

[[0.1304347826086958 0.17142857142857149]
 [0.43478260869565233 0.5428571428571427]]


# <font color='red'>Standard Scaler</font>

In [35]:
from sklearn.preprocessing import StandardScaler
sta = StandardScaler()
X_train[:, 3:] = sta.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sta.transform(X_test[:, 3:])

In [36]:
print(X_train[:, 3:])

[[-0.1915918438457856 -1.0781259408412427]
 [-0.014117293757057902 -0.07013167641635401]
 [0.5667085065333239 0.6335624327104546]
 [-0.3045301939022488 -0.30786617274297895]
 [-1.901801144700799 -1.4204636155515822]
 [1.1475343068237056 1.2326533634535488]
 [1.4379472069688966 1.5749910381638883]
 [-0.7401495441200352 -0.5646194287757336]]


In [37]:
print(X_test[:, 3:])

[[-1.4661817944830127 -0.9069571034860731]
 [-0.44973664397484425 0.20564033932253029]]
